[build-system]
requires = [
#    "setuptools>=42",
#    "wheel",
    "scikit-build>=0.13",
    "cmake>=3.16",
#    "pytest",
    "ninja",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Python >= 3.7, skip 32bit
skip = "cp36-* *-win32 *-manylinux_i686"
build = "cp38-*"
test-requires = "pytest"
test-command = "pytest {project}/tests"

# Run multiple commands using an array
before-all = [
    #    "apt-get python3-numpy libcairo2-dev zlib1g-dev libomp-dev -y",
    "apt-get update",
    "apt-get install python3-dev -y",
    "apt-get install python3-numpy -y",
    "apt-get install libcairo2-dev -y",
]

# Install system library
[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_24"

