[build-system]
requires = [
    "setuptools>=42",
    "scikit-build>=0.13",
    "wheel",
    "cmake>=3.16",
    "ninja",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Python >= 3.7, skip 32bit
skip = "cp36-* *-win32 *-manylinux_i686"
build = "cp38-*"
test-requires = "pytest"
test-command = "pytest {project}/tests"
build-verbosity = 3
before-build = [
    #"pip install setuptools",
    #"pip install scikit-build"
]
environment = { CMAKE_ARGS="-DCMAKE_BUILD_TARGET=_chemivec -DCIBUILDWHEEL=1" }

# Windows
[tool.cibuildwheel.windows]

# Linux
[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_24"
environment-pass = ["CMAKE_ARGS"]

before-all = [
    #"apt-get update",
    #"pip install setuptools"
    #"pip install scikit-build"
    #"apt-get install python3-dev -y",
    #"apt-get install python3-numpy -y",
    #"apt-get install libcairo2-dev -y",
]
