[project]
name="chemivec"
version="0.1.0"
requires-python = ">=3.8"
dependencies = [
    'numpy>=1.7',
    'pandas'
]

[build-system]
requires = [
    "scikit-build-core",
    "numpy>=1.7"
]
requires-python = ">=3.8"
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.verbose = true
#cmake.args = ["--target _chemivec"]
wheel.packages = ["src/chemivec"]
sdist.exclude = ["*unity*"]

build-dir = "build"

# old skbuild
#[build-system]
#requires = [
#    "setuptools>=42",
#    "scikit-build>=0.13",
#    "wheel",
#    "cmake>=3.16",
#    "ninja",
#    "numpy"
#]
#build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Python >= 3.7, skip 32bit
skip = "cp36-* *-win32 *-manylinux_i686"
build = "cp38-*"
test-requires = "pytest"
test-command = "pytest {project}/tests"
build-verbosity = 1
before-build = [
    #"pip install setuptools",
    #"pip install scikit-build"
]
environment = { CMAKE_ARGS="-DCIBUILDWHEEL=1" }

# Windows
[tool.cibuildwheel.windows]

# Linux
[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_24"
environment-pass = ["CMAKE_ARGS"]

before-all = [
    #"apt-get update",
    #"pip install setuptools"
    #"pip install scikit-build"
    #"apt-get install python3-dev -y",
    #"apt-get install python3-numpy -y",
    #"apt-get install libcairo2-dev -y",
]
