name: Build

defaults:
  run:
    shell: bash

on:
  push
#  release:
#    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ubuntu-20.04]
        os: [windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          gcc --version

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CC: gcc
          CXX: gxx
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
